[project]
name = "cv"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch>=2.7.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]

[tool.ruff]
target-version = "py313"  # minimum

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
